//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPurchaseInvHeader
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", ConfigurationName="WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port")]
    public interface WSPurchInvHeaderInterm_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.Read_Result> ReadAsync(WSPurchaseInvHeader.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.ReadByRecId_Result> ReadByRecIdAsync(WSPurchaseInvHeader.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.ReadMultiple_Result> ReadMultipleAsync(WSPurchaseInvHeader.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.IsUpdated_Result> IsUpdatedAsync(WSPurchaseInvHeader.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(WSPurchaseInvHeader.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.Create_Result> CreateAsync(WSPurchaseInvHeader.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.CreateMultiple_Result> CreateMultipleAsync(WSPurchaseInvHeader.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.Update_Result> UpdateAsync(WSPurchaseInvHeader.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.UpdateMultiple_Result> UpdateMultipleAsync(WSPurchaseInvHeader.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.Delete_Result> DeleteAsync(WSPurchaseInvHeader.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm")]
    public partial class WSPurchInvHeaderInterm
    {
        
        private string keyField;
        
        private string noField;
        
        private string pay_to_Vendor_NoField;
        
        private string pay_to_NameField;
        
        private string regionCode20Field;
        
        private string functionAreaCode20Field;
        
        private string responsabilityCenterCode20Field;
        
        private string locationCodeField;
        
        private string your_ReferenceField;
        
        private string observacoesField;
        
        private string purchaser_CodeField;
        
        private string n_ConsultaField;
        
        private System.DateTime expected_Receipt_DateField;
        
        private bool expected_Receipt_DateFieldSpecified;
        
        private string responsibility_CenterField;
        
        private string v_Prop_NumField;
        
        private string ship_to_NameField;
        
        private string ship_to_Name_2Field;
        
        private string ship_to_AddressField;
        
        private string ship_to_Address_2Field;
        
        private string ship_to_CityField;
        
        private string ship_to_ContactField;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_CountyField;
        
        private string ship_to_Country_Region_CodeField;
        
        private string requisition_NoField;
        
        private string payment_Terms_CodeField;
        
        private Mercado_Local_Regiao mercado_Local_RegiaoField;
        
        private bool mercado_Local_RegiaoFieldSpecified;
        
        private Motivo_Anulacao_Encomenda motivo_Anulacao_EncomendaField;
        
        private bool motivo_Anulacao_EncomendaFieldSpecified;
        
        private string encomenda_Origem_NAV17Field;
        
        private string utilizador_CriacaoField;
        
        private bool prices_Including_VATField;
        
        private bool prices_Including_VATFieldSpecified;
        
        private bool down_PaymentField;
        
        private bool down_PaymentFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Pay_to_Vendor_No
        {
            get
            {
                return this.pay_to_Vendor_NoField;
            }
            set
            {
                this.pay_to_Vendor_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Pay_to_Name
        {
            get
            {
                return this.pay_to_NameField;
            }
            set
            {
                this.pay_to_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RegionCode20
        {
            get
            {
                return this.regionCode20Field;
            }
            set
            {
                this.regionCode20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FunctionAreaCode20
        {
            get
            {
                return this.functionAreaCode20Field;
            }
            set
            {
                this.functionAreaCode20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ResponsabilityCenterCode20
        {
            get
            {
                return this.responsabilityCenterCode20Field;
            }
            set
            {
                this.responsabilityCenterCode20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Your_Reference
        {
            get
            {
                return this.your_ReferenceField;
            }
            set
            {
                this.your_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Observacoes
        {
            get
            {
                return this.observacoesField;
            }
            set
            {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Purchaser_Code
        {
            get
            {
                return this.purchaser_CodeField;
            }
            set
            {
                this.purchaser_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string N_Consulta
        {
            get
            {
                return this.n_ConsultaField;
            }
            set
            {
                this.n_ConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=12)]
        public System.DateTime Expected_Receipt_Date
        {
            get
            {
                return this.expected_Receipt_DateField;
            }
            set
            {
                this.expected_Receipt_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Expected_Receipt_DateSpecified
        {
            get
            {
                return this.expected_Receipt_DateFieldSpecified;
            }
            set
            {
                this.expected_Receipt_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Responsibility_Center
        {
            get
            {
                return this.responsibility_CenterField;
            }
            set
            {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string V_Prop_Num
        {
            get
            {
                return this.v_Prop_NumField;
            }
            set
            {
                this.v_Prop_NumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Ship_to_Name
        {
            get
            {
                return this.ship_to_NameField;
            }
            set
            {
                this.ship_to_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Ship_to_Name_2
        {
            get
            {
                return this.ship_to_Name_2Field;
            }
            set
            {
                this.ship_to_Name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Ship_to_Address
        {
            get
            {
                return this.ship_to_AddressField;
            }
            set
            {
                this.ship_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Ship_to_Address_2
        {
            get
            {
                return this.ship_to_Address_2Field;
            }
            set
            {
                this.ship_to_Address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Ship_to_City
        {
            get
            {
                return this.ship_to_CityField;
            }
            set
            {
                this.ship_to_CityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Ship_to_Contact
        {
            get
            {
                return this.ship_to_ContactField;
            }
            set
            {
                this.ship_to_ContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Ship_to_Post_Code
        {
            get
            {
                return this.ship_to_Post_CodeField;
            }
            set
            {
                this.ship_to_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Ship_to_County
        {
            get
            {
                return this.ship_to_CountyField;
            }
            set
            {
                this.ship_to_CountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Ship_to_Country_Region_Code
        {
            get
            {
                return this.ship_to_Country_Region_CodeField;
            }
            set
            {
                this.ship_to_Country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Requisition_No
        {
            get
            {
                return this.requisition_NoField;
            }
            set
            {
                this.requisition_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Payment_Terms_Code
        {
            get
            {
                return this.payment_Terms_CodeField;
            }
            set
            {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public Mercado_Local_Regiao Mercado_Local_Regiao
        {
            get
            {
                return this.mercado_Local_RegiaoField;
            }
            set
            {
                this.mercado_Local_RegiaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Mercado_Local_RegiaoSpecified
        {
            get
            {
                return this.mercado_Local_RegiaoFieldSpecified;
            }
            set
            {
                this.mercado_Local_RegiaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public Motivo_Anulacao_Encomenda Motivo_Anulacao_Encomenda
        {
            get
            {
                return this.motivo_Anulacao_EncomendaField;
            }
            set
            {
                this.motivo_Anulacao_EncomendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Motivo_Anulacao_EncomendaSpecified
        {
            get
            {
                return this.motivo_Anulacao_EncomendaFieldSpecified;
            }
            set
            {
                this.motivo_Anulacao_EncomendaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Encomenda_Origem_NAV17
        {
            get
            {
                return this.encomenda_Origem_NAV17Field;
            }
            set
            {
                this.encomenda_Origem_NAV17Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Utilizador_Criacao
        {
            get
            {
                return this.utilizador_CriacaoField;
            }
            set
            {
                this.utilizador_CriacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool Prices_Including_VAT
        {
            get
            {
                return this.prices_Including_VATField;
            }
            set
            {
                this.prices_Including_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prices_Including_VATSpecified
        {
            get
            {
                return this.prices_Including_VATFieldSpecified;
            }
            set
            {
                this.prices_Including_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool Down_Payment
        {
            get
            {
                return this.down_PaymentField;
            }
            set
            {
                this.down_PaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Down_PaymentSpecified
        {
            get
            {
                return this.down_PaymentFieldSpecified;
            }
            set
            {
                this.down_PaymentFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm")]
    public enum Mercado_Local_Regiao
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Lisboa,
        
        /// <remarks/>
        Porto,
        
        /// <remarks/>
        Coimbra,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm")]
    public enum Motivo_Anulacao_Encomenda
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Orçamento_rectificativo,
        
        /// <remarks/>
        Solicitação_Área,
        
        /// <remarks/>
        Reenvio_Fornecedor_Alternativo,
        
        /// <remarks/>
        Alteração_Câmbio,
        
        /// <remarks/>
        Erro_do_Utilizador,
        
        /// <remarks/>
        Preços_Incorretos,
        
        /// <remarks/>
        Quantidades_Incorretas,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm")]
    public partial class WSPurchInvHeaderInterm_Filter
    {
        
        private WSPurchInvHeaderInterm_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WSPurchInvHeaderInterm_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm")]
    public enum WSPurchInvHeaderInterm_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Pay_to_Vendor_No,
        
        /// <remarks/>
        Pay_to_Name,
        
        /// <remarks/>
        RegionCode20,
        
        /// <remarks/>
        FunctionAreaCode20,
        
        /// <remarks/>
        ResponsabilityCenterCode20,
        
        /// <remarks/>
        LocationCode,
        
        /// <remarks/>
        Your_Reference,
        
        /// <remarks/>
        Observacoes,
        
        /// <remarks/>
        Purchaser_Code,
        
        /// <remarks/>
        N_Consulta,
        
        /// <remarks/>
        Expected_Receipt_Date,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        V_Prop_Num,
        
        /// <remarks/>
        Ship_to_Name,
        
        /// <remarks/>
        Ship_to_Name_2,
        
        /// <remarks/>
        Ship_to_Address,
        
        /// <remarks/>
        Ship_to_Address_2,
        
        /// <remarks/>
        Ship_to_City,
        
        /// <remarks/>
        Ship_to_Contact,
        
        /// <remarks/>
        Ship_to_Post_Code,
        
        /// <remarks/>
        Ship_to_County,
        
        /// <remarks/>
        Ship_to_Country_Region_Code,
        
        /// <remarks/>
        Requisition_No,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Mercado_Local_Regiao,
        
        /// <remarks/>
        Motivo_Anulacao_Encomenda,
        
        /// <remarks/>
        Encomenda_Origem_NAV17,
        
        /// <remarks/>
        Utilizador_Criacao,
        
        /// <remarks/>
        Prices_Including_VAT,
        
        /// <remarks/>
        Down_Payment,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm;
        
        public Read_Result()
        {
        }
        
        public Read_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm)
        {
            this.WSPurchInvHeaderInterm = WSPurchInvHeaderInterm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm)
        {
            this.WSPurchInvHeaderInterm = WSPurchInvHeaderInterm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(WSPurchaseInvHeader.WSPurchInvHeaderInterm_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm;
        
        public Create()
        {
        }
        
        public Create(WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm)
        {
            this.WSPurchInvHeaderInterm = WSPurchInvHeaderInterm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm;
        
        public Create_Result()
        {
        }
        
        public Create_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm)
        {
            this.WSPurchInvHeaderInterm = WSPurchInvHeaderInterm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List)
        {
            this.WSPurchInvHeaderInterm_List = WSPurchInvHeaderInterm_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List)
        {
            this.WSPurchInvHeaderInterm_List = WSPurchInvHeaderInterm_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm;
        
        public Update()
        {
        }
        
        public Update(WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm)
        {
            this.WSPurchInvHeaderInterm = WSPurchInvHeaderInterm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm;
        
        public Update_Result()
        {
        }
        
        public Update_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm WSPurchInvHeaderInterm)
        {
            this.WSPurchInvHeaderInterm = WSPurchInvHeaderInterm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List)
        {
            this.WSPurchInvHeaderInterm_List = WSPurchInvHeaderInterm_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(WSPurchaseInvHeader.WSPurchInvHeaderInterm[] WSPurchInvHeaderInterm_List)
        {
            this.WSPurchInvHeaderInterm_List = WSPurchInvHeaderInterm_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/wspurchinvheaderinterm", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface WSPurchInvHeaderInterm_PortChannel : WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class WSPurchInvHeaderInterm_PortClient : System.ServiceModel.ClientBase<WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port>, WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSPurchInvHeaderInterm_PortClient() : 
                base(WSPurchInvHeaderInterm_PortClient.GetDefaultBinding(), WSPurchInvHeaderInterm_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSPurchInvHeaderInterm_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPurchInvHeaderInterm_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(WSPurchInvHeaderInterm_PortClient.GetBindingForEndpoint(endpointConfiguration), WSPurchInvHeaderInterm_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPurchInvHeaderInterm_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSPurchInvHeaderInterm_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPurchInvHeaderInterm_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSPurchInvHeaderInterm_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPurchInvHeaderInterm_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.Read_Result> WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port.ReadAsync(WSPurchaseInvHeader.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.Read_Result> ReadAsync(string No)
        {
            WSPurchaseInvHeader.Read inValue = new WSPurchaseInvHeader.Read();
            inValue.No = No;
            return ((WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.ReadByRecId_Result> WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port.ReadByRecIdAsync(WSPurchaseInvHeader.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            WSPurchaseInvHeader.ReadByRecId inValue = new WSPurchaseInvHeader.ReadByRecId();
            inValue.recId = recId;
            return ((WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.ReadMultiple_Result> WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port.ReadMultipleAsync(WSPurchaseInvHeader.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.ReadMultiple_Result> ReadMultipleAsync(WSPurchaseInvHeader.WSPurchInvHeaderInterm_Filter[] filter, string bookmarkKey, int setSize)
        {
            WSPurchaseInvHeader.ReadMultiple inValue = new WSPurchaseInvHeader.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.IsUpdated_Result> WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port.IsUpdatedAsync(WSPurchaseInvHeader.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            WSPurchaseInvHeader.IsUpdated inValue = new WSPurchaseInvHeader.IsUpdated();
            inValue.Key = Key;
            return ((WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.GetRecIdFromKey_Result> WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port.GetRecIdFromKeyAsync(WSPurchaseInvHeader.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            WSPurchaseInvHeader.GetRecIdFromKey inValue = new WSPurchaseInvHeader.GetRecIdFromKey();
            inValue.Key = Key;
            return ((WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.Create_Result> CreateAsync(WSPurchaseInvHeader.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.CreateMultiple_Result> CreateMultipleAsync(WSPurchaseInvHeader.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.Update_Result> UpdateAsync(WSPurchaseInvHeader.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.UpdateMultiple_Result> UpdateMultipleAsync(WSPurchaseInvHeader.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSPurchaseInvHeader.Delete_Result> WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port.DeleteAsync(WSPurchaseInvHeader.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSPurchaseInvHeader.Delete_Result> DeleteAsync(string Key)
        {
            WSPurchaseInvHeader.Delete inValue = new WSPurchaseInvHeader.Delete();
            inValue.Key = Key;
            return ((WSPurchaseInvHeader.WSPurchInvHeaderInterm_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPurchInvHeaderInterm_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPurchInvHeaderInterm_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://such-navdev.such.local:8047/DynamicsNAV100_QUAL/WS/SUCH - QUALIDADE/Page/W" +
                        "SPurchInvHeaderInterm");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSPurchInvHeaderInterm_PortClient.GetBindingForEndpoint(EndpointConfiguration.WSPurchInvHeaderInterm_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSPurchInvHeaderInterm_PortClient.GetEndpointAddress(EndpointConfiguration.WSPurchInvHeaderInterm_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            WSPurchInvHeaderInterm_Port,
        }
    }
}
