using System;
using System.Collections.Generic;

namespace Hydra.Such.Data.Evolution.Database
{
    public partial class JobJournalLine
    {
        public byte[] Timestamp { get; set; }
        public string NumMec { get; set; }
        public int LineNo { get; set; }
        public string JobNo { get; set; }
        public DateTime PostingDate { get; set; }
        public string DocumentNo { get; set; }
        public int Type { get; set; }
        public string No { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal DirectUnitCostLcy { get; set; }
        public decimal UnitCostLcy { get; set; }
        public decimal TotalCostLcy { get; set; }
        public decimal UnitPriceLcy { get; set; }
        public decimal TotalPriceLcy { get; set; }
        public string ResourceGroupNo { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string LocationCode { get; set; }
        public byte Chargeable { get; set; }
        public string PostingGroup { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string WorkTypeCode { get; set; }
        public string CustomerPriceGroup { get; set; }
        public int AppliesToEntry { get; set; }
        public int EntryType { get; set; }
        public string SourceCode { get; set; }
        public string ReasonCode { get; set; }
        public int RecurringMethod { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string RecurringFrequency { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string GenProdPostingGroup { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string CountryRegionCode { get; set; }
        public string EntryExitPoint { get; set; }
        public DateTime DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string SerialNo { get; set; }
        public string PostingNoSeries { get; set; }
        public string SourceCurrencyCode { get; set; }
        public decimal SourceCurrencyTotalCost { get; set; }
        public decimal SourceCurrencyTotalPrice { get; set; }
        public decimal SourceCurrencyLineAmount { get; set; }
        public string JobTaskNo { get; set; }
        public decimal TotalCost { get; set; }
        public decimal UnitPrice { get; set; }
        public int LineType { get; set; }
        public int AppliesFromEntry { get; set; }
        public byte JobPostingOnly { get; set; }
        public decimal LineDiscount { get; set; }
        public decimal LineDiscountAmount { get; set; }
        public string CurrencyCode { get; set; }
        public decimal LineAmount { get; set; }
        public decimal CurrencyFactor { get; set; }
        public decimal UnitCost { get; set; }
        public decimal LineAmountLcy { get; set; }
        public decimal LineDiscountAmountLcy { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal CostFactor { get; set; }
        public string Description2 { get; set; }
        public int LedgerEntryType { get; set; }
        public int LedgerEntryNo { get; set; }
        public string VariantCode { get; set; }
        public string BinCode { get; set; }
        public decimal QtyPerUnitOfMeasure { get; set; }
        public decimal QuantityBase { get; set; }
        public string ServiceOrderNo { get; set; }
        public string PostedServiceShipmentNo { get; set; }
        public string LotNo { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string Subcontratação { get; set; }
        public byte SkipMessage { get; set; }
        public string CentralIncineração { get; set; }
        public string NºGuiaResíduosGar { get; set; }
        public string NºGuiaExterna { get; set; }
        public int DiaDaSemana { get; set; }
        public string LocalRecolha { get; set; }
        public DateTime HoraDeRegisto { get; set; }
        public string FacturaANºCliente { get; set; }
        public string Classe { get; set; }
        public string RequisitionNo { get; set; }
        public int RequisitionLineNo { get; set; }
        public string CódCategoriaProd { get; set; }
        public string CódGrupoProd { get; set; }
        public string NºCartãoUtente { get; set; }
        public string SalespersPurchCode { get; set; }
        public string Utilizador { get; set; }
        public byte ValidaMsgRegisto { get; set; }
        public string CodigoOrcamento { get; set; }
        public byte ErrorOnPosting { get; set; }
        public string ErrorMessage { get; set; }
        public byte CreatedFromSync { get; set; }
        public long ChaveOrcamento { get; set; }
        public string Motorista { get; set; }
        public int NºLinhaFolha { get; set; }
        public int Estado { get; set; }
        public string TipoRefeição { get; set; }
        public int TipoMovRefeitorio { get; set; }
        public string NºGuiaRemessa { get; set; }
        public string DestinoFinalResiduos { get; set; }
        public string Tipologia { get; set; }
        public int TipoManutencao { get; set; }
        public byte FacturacaoAutorizada { get; set; }
        public string NomeSeccaoProjecto { get; set; }
        public decimal PesagemCliente { get; set; }
        public string CodServCliente { get; set; }
        public string DesServCliente { get; set; }
        public int TipoRecurso { get; set; }
        public int ObjectRefType { get; set; }
        public string ObjectRefNo { get; set; }
        public string DescriçãoObjectoRef { get; set; }
        public byte AjudaCusto { get; set; }
        public byte Mc { get; set; }
        public string ShortcutDimension3Code { get; set; }
        public string GrupoServiço { get; set; }
        public string Matricula { get; set; }
        public int ObjectType { get; set; }
        public string ObjectNo { get; set; }
        public int NºLinhaOm { get; set; }
        public decimal PesoTotal { get; set; }
        public string DescriçãoTipo { get; set; }
        public string DescriçãoMarca { get; set; }
        public string DescriçãoModelo { get; set; }
        public long NºFolhaDeHoras { get; set; }
        public byte BAjmo { get; set; }
        public byte BOrçamento { get; set; }
        public decimal DescontoVenda { get; set; }
        public string RequisiçãoInterna { get; set; }
        public string NºFuncionario { get; set; }
        public string Description22 { get; set; }
        public int DevoluçãoMovProjecto { get; set; }
        public int JleOrigem { get; set; }
        public string TransfParaProj { get; set; }
        public byte PurchaseDocument { get; set; }
        public byte JournalDocument { get; set; }
        public DateTime DataDespesa { get; set; }
        public int NºPreRegisto { get; set; }
        public int FromPlanningLineNo { get; set; }
        public DateTime DataConsumo { get; set; }
        public byte RegistoTemp { get; set; }
        public decimal Vat { get; set; }
        public byte ImportadoManage { get; set; }
        public string DocumentoOriginal { get; set; }
        public string DocumentoCorrigido { get; set; }
        public byte AcertoPrecos { get; set; }
        public DateTime DataDocumentoCorrigido { get; set; }
        public byte MovInverso { get; set; }
        public int? IdCliente { get; set; }
        public int? IdInstituicao { get; set; }
        public int? IdServico { get; set; }
    }
}
