using System;
using System.Collections.Generic;

namespace Hydra.Such.Data.Evolution.Database
{
    public partial class MovProjectoAutorizadosFact
    {
        public byte[] Timestamp { get; set; }
        public int EntryNo { get; set; }
        public string JobNo { get; set; }
        public DateTime PostingDate { get; set; }
        public string DocumentNo { get; set; }
        public int Type { get; set; }
        public string No { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal DirectUnitCost { get; set; }
        public decimal UnitCost { get; set; }
        public decimal TotalCost { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public string ResourceGroupNo { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string LocationCode { get; set; }
        public byte Chargeable { get; set; }
        public string JobPostingGroup { get; set; }
        public string GlobalDimension1Code { get; set; }
        public string GlobalDimension2Code { get; set; }
        public string WorkTypeCode { get; set; }
        public string CustomerPriceGroup { get; set; }
        public string UserId { get; set; }
        public string SourceCode { get; set; }
        public byte RelatedToBudget { get; set; }
        public string PhaseCode { get; set; }
        public string TaskCode { get; set; }
        public string StepCode { get; set; }
        public decimal AmtToPostToGL { get; set; }
        public decimal AmtPostedToGL { get; set; }
        public decimal AmtToRecognize { get; set; }
        public decimal AmtRecognized { get; set; }
        public int EntryType { get; set; }
        public byte Positive { get; set; }
        public byte Open { get; set; }
        public decimal RemainingAmount { get; set; }
        public int ClosedByEntryNo { get; set; }
        public DateTime ClosedAtDate { get; set; }
        public decimal ClosedByAmount { get; set; }
        public string AppliesToId { get; set; }
        public string JournalBatchName { get; set; }
        public string ReasonCode { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string CountryCode { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string GenProdPostingGroup { get; set; }
        public DateTime DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string NoSeries { get; set; }
        public decimal AddCurrAmtPostedToGL { get; set; }
        public string JobTaskNo { get; set; }
        public int LedgerEntryType { get; set; }
        public int LedgerEntryNo { get; set; }
        public decimal QtyPerUnitOfMeasure { get; set; }
        public string ServiceOrderNo { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string Subcontratação { get; set; }
        public string CentralIncineração { get; set; }
        public string NºGuiaResíduosGar { get; set; }
        public string NºGuiaExterna { get; set; }
        public int DiaDaSemana { get; set; }
        public string LocalRecolha { get; set; }
        public int TipoProjecto { get; set; }
        public DateTime HoraDeRegisto { get; set; }
        public string FacturaANºCliente { get; set; }
        public string Classe { get; set; }
        public string RequisitionNo { get; set; }
        public int RequisitionLineNo { get; set; }
        public string CódCategoriaProd { get; set; }
        public string CódGrupoProd { get; set; }
        public string NºCartãoUtente { get; set; }
        public string CodigoOrcamento { get; set; }
        public long ChaveOrcamento { get; set; }
        public byte FacturaCriada { get; set; }
        public string Motorista { get; set; }
        public decimal ValorDescQuantidade { get; set; }
        public int NºLinhaFolha { get; set; }
        public string TipoRefeição { get; set; }
        public string Tipologia { get; set; }
        public string ObjectRefNo { get; set; }
        public int ObjectRefType { get; set; }
        public int Opção { get; set; }
        public int MoLineNo { get; set; }
        public string MoNo { get; set; }
        public int MoTaskLineNo { get; set; }
        public int MoToolLineNo { get; set; }
        public int MoComponentLineNo { get; set; }
        public int MoCostLineNo { get; set; }
        public int ObjectType { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectDescription { get; set; }
        public string FlNo { get; set; }
        public string FlDescription { get; set; }
        public int MaintEntryNo { get; set; }
        public string Utilizador { get; set; }
        public int TipoManutencao { get; set; }
        public byte FacturacaoAutorizada { get; set; }
        public DateTime DataAutorizacaoFacturacao { get; set; }
        public string UtilizadorIdAutorizacao { get; set; }
        public string ContractNo { get; set; }
        public string GrupoServiço { get; set; }
        public decimal PesagemCliente { get; set; }
        public byte EnviadoTr { get; set; }
        public string CodServCliente { get; set; }
        public string DesServCliente { get; set; }
        public byte LinhaAutFac { get; set; }
        public int TipoRecurso { get; set; }
        public string LinhaOrdemManutenção { get; set; }
        public byte RegistadoMc { get; set; }
        public string GlobalDimension3Code { get; set; }
        public string Matricula { get; set; }
        public long NºOrdemAs4001 { get; set; }
        public int NºLinhaOm { get; set; }
        public decimal Total1 { get; set; }
        public decimal TotalEquipamento { get; set; }
        public byte BAjmo { get; set; }
        public byte BOrçamento { get; set; }
        public decimal DescontoVenda { get; set; }
        public string RequisiçãoInterna { get; set; }
        public string NºFuncionario { get; set; }
        public int GrupoFactura { get; set; }
        public DateTime DataConsumo { get; set; }
        public string Description2 { get; set; }
    }
}
