using System;
using System.Collections.Generic;

namespace Hydra.Such.Data.Evolution.Database
{
    public partial class PostedMaintenanceOrder
    {
        public byte[] Timestamp { get; set; }
        public int DocumentType { get; set; }
        public string No { get; set; }
        public string Description { get; set; }
        public int ObjectRefType { get; set; }
        public string ObjectRefNo { get; set; }
        public string ObjectRefDescription { get; set; }
        public string ComponentOf { get; set; }
        public string OrderType { get; set; }
        public string MaintenanceActivity { get; set; }
        public int SourceDocType { get; set; }
        public string SourceDocNo { get; set; }
        public string ContractNo { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public string SuspendedOrderReason { get; set; }
        public string ResponsibilityCenter { get; set; }
        public DateTime LastDateModified { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerPostCode { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string CustomerEMail { get; set; }
        public string CustomerShipToCode { get; set; }
        public string CustomerFaxNo { get; set; }
        public string CustomerReference { get; set; }
        public string CustomerContactName { get; set; }
        public string CustomerCountryCode { get; set; }
        public DateTime PostingDate { get; set; }
        public string CustomerCounty { get; set; }
        public string JobNo { get; set; }
        public int ApplicationMethod { get; set; }
        public string LanguageCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalQtyToInvoice { get; set; }
        public string RespCenterName { get; set; }
        public string RespCenterName2 { get; set; }
        public string FaxNo { get; set; }
        public string County { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string PhoneNo { get; set; }
        public string Reference { get; set; }
        public string FaNo { get; set; }
        public string FlNo { get; set; }
        public string FlDescription { get; set; }
        public byte Failed { get; set; }
        public string ResponsibleEmployee { get; set; }
        public string EnteredBy { get; set; }
        public string ResourceNo { get; set; }
        public string PlannerGroupNo { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime OrderTime { get; set; }
        public DateTime DocumentDate { get; set; }
        public DateTime ExpectedFinishingDate { get; set; }
        public DateTime ExpectedFinishingTime { get; set; }
        public DateTime ExpectedStartingDate { get; set; }
        public DateTime ExpectedStartingTime { get; set; }
        public DateTime StartingDate { get; set; }
        public DateTime StartingTime { get; set; }
        public decimal ResponseTimeHours { get; set; }
        public decimal MaintenanceTimeHours { get; set; }
        public DateTime FinishingDate { get; set; }
        public DateTime FinishingTime { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string CustomerPriceGroup { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string VatRegistrationNo { get; set; }
        public string PurchaserCode { get; set; }
        public string PlannedOrderNo { get; set; }
        public string NoSeries { get; set; }
        public int Reserve { get; set; }
        public string Validade { get; set; }
        public byte Budget { get; set; }
        public string FaPostingGroup { get; set; }
        public string WorkCenterNo { get; set; }
        public string MachineCenterNo { get; set; }
        public decimal ExpServQty { get; set; }
        public decimal FinishingTimeHours { get; set; }
        public string TipoContactoCliente { get; set; }
        public string CustomerDocNo { get; set; }
        public string JobPostingGroup { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToName { get; set; }
        public string ShipToName2 { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToPostCode { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToContact { get; set; }
        public string ShortcutDimension3Code { get; set; }
        public string ShortcutDimension4Code { get; set; }
        public DateTime DataFecho { get; set; }
        public DateTime HoraFecho { get; set; }
        public string Loc1 { get; set; }
        public DateTime DataEntrada { get; set; }
        public string NºGeste { get; set; }
        public DateTime DataEntrega { get; set; }
        public DateTime DataSaída { get; set; }
        public string Loc2 { get; set; }
        public string Loc3 { get; set; }
        public string Descrição1 { get; set; }
        public string Descrição2 { get; set; }
        public string Descrição3 { get; set; }
        public int NºLinhaContrato { get; set; }
        public DateTime DataReabertura { get; set; }
        public DateTime HoraReabertura { get; set; }
        public string NºAntigoAs400 { get; set; }
        public DateTime DataPedidoReparação { get; set; }
        public DateTime HoraPedidoReparação { get; set; }
        public string FechadoPor { get; set; }
        public string ReabertoPor { get; set; }
        public string ConcluidoPor { get; set; }
        public DateTime DataPedido { get; set; }
        public DateTime DataValidade { get; set; }
        public DateTime ValidadePedido { get; set; }
        public decimal ValorProjecto { get; set; }
        public string DeliberaçãoCa { get; set; }
        public byte ServInternosRequisições { get; set; }
        public byte ServInternosFolhasDeObra { get; set; }
        public byte ServInternosDébInternos { get; set; }
        public byte MãoDeObraEDeslocações { get; set; }
        public string ConfigResponsavel { get; set; }
        public DateTime DataUltimoMail { get; set; }
        public string UserChefeProjecto { get; set; }
        public DateTime DataChefeProjecto { get; set; }
        public string UserResponsavel { get; set; }
        public DateTime DataResponsavel { get; set; }
        public DateTime DataFacturação { get; set; }
        public string NoCompromisso { get; set; }
        public string NoDocumentoContactoInicial { get; set; }
        public string TécnicoExecutante { get; set; }
        public string TipoContactoClienteInicial { get; set; }
    }
}
