using Hydra.Such.Data.Database;
using Hydra.Such.Data.ViewModel.CCP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace Hydra.Such.Data.ViewModel.CCP
{
    public static class CCPFunctions
    {
        #region functions to map the Entity Framework objects to Json-friendly objects
        // this function receives an ProcedimentosCcp objet and maps it to a ProcedimentosCccpView object
        public static ProcedimentoCCPView CastProcCcpToProcCcpView(ProcedimentosCcp proc)
        {
            return (new ProcedimentoCCPView
            {
                No = proc.Nº,
                Tipo = proc.Tipo,
                Ano = proc.Ano,
                Referencia = proc.Referência,
                CodigoRegiao = proc.CódigoRegião,
                CodigoAreaFuncional = proc.CódigoÁreaFuncional,
                CodigoCentroResponsabilidade = proc.CódigoCentroResponsabilidade,
                Estado = proc.Estado,
                DataCriacao = proc.DataCriação,
                Imobilizado = proc.Imobilizado,
                ComentarioEstado = proc.ComentárioEstado,
                Anexos = proc.Anexos,
                DataHoraEstado = proc.DataHoraEstado,
                UtilizadorEstado = proc.UtilizadorEstado,
                CondicoesDePagamento = proc.CondiçõesDePagamento,
                NomeProcesso = proc.NomeProcesso,
                GestorProcesso = proc.GestorProcesso,
                TipoProcedimento = proc.TipoProcedimento,
                InformacaoTecnica = proc.InformaçãoTécnica,
                FundamentacaoAquisicao = proc.FundamentaçãoAquisição,
                PrecoBase = proc.PreçoBase,
                ValorPrecoBase = proc.ValorPreçoBase,
                Negociacao = proc.Negociação,
                CriteriosAdjudicacao = proc.CritériosAdjudicação,
                Prazo = proc.Prazo,
                PrecoMaisBaixo = proc.PreçoMaisBaixo,
                PropostaEconMaisVantajosa = proc.PropostaEconMaisVantajosa,
                PropostaVariante = proc.PropostaVariante,
                AbertoFechadoAoMercado = proc.AbertoFechadoAoMercado,
                PrazoEntrega = proc.PrazoEntrega,
                LocaisEntrega = proc.LocaisEntrega,
                ObservacoesAdicionais = proc.ObservaçõesAdicionais,
                EstimativaPreco = proc.EstimativaPreço,
                FornecedoresSugeridos = proc.FornecedoresSugeridos,
                FornecedorExclusivo = proc.FornecedorExclusivo,
                Interlocutor = proc.Interlocutor,
                DescPrecoMaisBaixo = proc.DescPreçoMaisBaixo,
                DescPropostaEconMaisVantajosa = proc.DescPropostaEconMaisVantajosa,
                DescPropostaVariante = proc.DescPropostaVariante,
                DescAbertoFechadoAoMercado = proc.DescAbertoFechadoAoMercado,
                DescFornecedorExclusivo = proc.DescFornecedorExclusivo,
                CriterioEscolhaProcedimento = proc.CritérioEscolhaProcedimento,
                DescEscolhaProcedimento = proc.DescEscolhaProcedimento,
                Juri = proc.Júri,
                ObjetoDoContrato = proc.ObjetoDoContrato,
                PreArea = proc.PréÁrea,
                SubmeterPreArea = proc.SubmeterPréÁrea,
                ValorDecisaoContratar = proc.ValorDecisãoContratar,
                ValorAdjudicacaoAnteriro = proc.ValorAdjudicaçãoAnteriro,
                ValorAdjudicacaoAtual = proc.ValorAdjudicaçãoAtual,
                DiferencaEuros = proc.DiferençaEuros,
                DiferencaPercent = proc.DiferençaPercent,
                WorkflowFinanceiros = proc.WorkflowFinanceiros,
                WorkflowJuridicos = proc.WorkflowJurídicos,
                WorkflowFinanceirosConfirm = proc.WorkflowFinanceirosConfirm,
                WorkflowJuridicosConfirm = proc.WorkflowJurídicosConfirm,
                AutorizacaoImobCa = proc.AutorizaçãoImobCa,
                AutorizacaoAberturaCa = proc.AutorizaçãoAberturaCa,
                AutorizacaoAquisicaoCa = proc.AutorizaçãoAquisiçãoCa,
                RejeicaoImobCa = proc.RejeiçãoImobCa,
                RejeicaoAberturaCa = proc.RejeiçãoAberturaCa,
                RejeicaoAquisicaoCa = proc.RejeiçãoAquisiçãoCa,
                DataAutorizacaoImobCa = proc.DataAutorizaçãoImobCa,
                DataAutorizacaoAbertCa = proc.DataAutorizaçãoAbertCa,
                DataAutorizacaoAquisiCa = proc.DataAutorizaçãoAquisiCa,
                RatificarCaAbertura = proc.RatificarCaAbertura,
                RatificarCaAdjudicacao = proc.RatificarCaAdjudicação,
                CaRatificar = proc.CaRatificar,
                CaDataRatificacaoAbert = proc.CaDataRatificaçãoAbert,
                CaDataRatificacaoAdjudic = proc.CaDataRatificaçãoAdjudic,
                No_Ata = proc.NºAta,
                DataAta = proc.DataAta,
                ComentarioPublicacao = proc.ComentárioPublicação,
                DataPublicacao = proc.DataPublicação,
                UtilizadorPublicacao = proc.UtilizadorPublicação,
                DataSistemaPublicacao = proc.DataSistemaPublicação,
                RecolhaComentario = proc.RecolhaComentário,
                DataRecolha = proc.DataRecolha,
                UtilizadorRecolha = proc.UtilizadorRecolha,
                DataSistemaRecolha = proc.DataSistemaRecolha,
                ComentarioRelatorioPreliminar = proc.ComentárioRelatórioPreliminar,
                DataValidRelatorioPreliminar = proc.DataValidRelatórioPreliminar,
                UtilizadorValidRelatorioPreliminar = proc.UtilizadorValidRelatórioPreliminar,
                DataSistemaValidRelatorioPreliminar = proc.DataSistemaValidRelatórioPreliminar,
                ComentarioAudienciaPrevia = proc.ComentárioAudiênciaPrévia,
                DataAudienciaPrevia = proc.DataAudiênciaPrévia,
                UtilizadorAudienciaPrevia = proc.UtilizadorAudiênciaPrévia,
                DataSistemaAudienciaPrevia = proc.DataSistemaAudiênciaPrévia,
                ComentarioRelatorioFinal = proc.ComentárioRelatórioFinal,
                DataRelatorioFinal = proc.DataRelatórioFinal,
                UtilizadorRelatorioFinal = proc.UtilizadorRelatórioFinal,
                DataSistemaRelatorioFinal = proc.DataSistemaRelatórioFinal,
                ComentarioNotificacao = proc.ComentárioNotificação,
                DataNotificacao = proc.DataNotificação,
                UtilizadorNotificacao = proc.UtilizadorNotificação,
                DataSistemaNotificacao = proc.DataSistemaNotificação,
                PrazoNotificacaoDias = proc.PrazoNotificaçãoDias,
                PercentExecucao = proc.PercentExecução,
                Arquivado = proc.Arquivado,
                DataFechoInicial = proc.DataFechoInicial,
                DataFechoPrevista = proc.DataFechoPrevista,
                No_DiasProcesso = proc.NºDiasProcesso,
                No_DiasAtraso = proc.NºDiasAtraso,
                Tratado = proc.Tratado,
                Fornecedor = proc.Fornecedor,
                Comentario = proc.Comentário,
                CaSuspenso = proc.CaSuspenso,
                CriticoAbertura = proc.CríticoAbertura,
                CriticoAdjudicacao = proc.CríticoAdjudicação,
                ObjetoDecisao = proc.ObjetoDecisão,
                RazaoNecessidade = proc.RazãoNecessidade,
                ProtocoloContrato = proc.ProtocoloContrato,
                AutorizacaoAdjudicacao = proc.AutorizaçãoAdjudicação,
                NaoAdjudicacaoEEncerramento = proc.NãoAdjudicaçãoEEncerramento,
                NaoAdjudicacaoESuspensao = proc.NãoAdjudicaçãoESuspensão,
                DataHoraCriacao = proc.DataHoraCriação,
                UtilizadorCriacao = proc.UtilizadorCriação,
                DataHoraModificacao = proc.DataHoraModificação,
                UtilizadorModificacao = proc.UtilizadorModificação
            });
        }

        // this function receives an ProcedimentosCcpView object and maps it to a ProcedimentosCcp object
        public static ProcedimentosCcp CastProcCcpViewToProcCcp(ProcedimentoCCPView proc_view)
        {
            return (new ProcedimentosCcp
            {
                Nº = proc_view.No,
                Tipo = proc_view.Tipo,
                Ano = proc_view.Ano,
                Referência = proc_view.Referencia,
                CódigoRegião = proc_view.CodigoRegiao,
                CódigoÁreaFuncional = proc_view.CodigoAreaFuncional,
                CódigoCentroResponsabilidade = proc_view.CodigoCentroResponsabilidade,
                Estado = proc_view.Estado,
                DataCriação = proc_view.DataCriacao,
                Imobilizado = proc_view.Imobilizado,
                ComentárioEstado = proc_view.ComentarioEstado,
                Anexos = proc_view.Anexos,
                DataHoraEstado = proc_view.DataHoraEstado,
                UtilizadorEstado = proc_view.UtilizadorEstado,
                CondiçõesDePagamento = proc_view.CondicoesDePagamento,
                NomeProcesso = proc_view.NomeProcesso,
                GestorProcesso = proc_view.GestorProcesso,
                TipoProcedimento = proc_view.TipoProcedimento,
                InformaçãoTécnica = proc_view.InformacaoTecnica,
                FundamentaçãoAquisição = proc_view.FundamentacaoAquisicao,
                PreçoBase = proc_view.PrecoBase,
                ValorPreçoBase = proc_view.ValorPrecoBase,
                Negociação = proc_view.Negociacao,
                CritériosAdjudicação = proc_view.CriteriosAdjudicacao,
                Prazo = proc_view.Prazo,
                PreçoMaisBaixo = proc_view.PrecoMaisBaixo,
                PropostaEconMaisVantajosa = proc_view.PropostaEconMaisVantajosa,
                PropostaVariante = proc_view.PropostaVariante,
                AbertoFechadoAoMercado = proc_view.AbertoFechadoAoMercado,
                PrazoEntrega = proc_view.PrazoEntrega,
                LocaisEntrega = proc_view.LocaisEntrega,
                ObservaçõesAdicionais = proc_view.ObservacoesAdicionais,
                EstimativaPreço = proc_view.EstimativaPreco,
                FornecedoresSugeridos = proc_view.FornecedoresSugeridos,
                FornecedorExclusivo = proc_view.FornecedorExclusivo,
                Interlocutor = proc_view.Interlocutor,
                DescPreçoMaisBaixo = proc_view.DescPrecoMaisBaixo,
                DescPropostaEconMaisVantajosa = proc_view.DescPropostaEconMaisVantajosa,
                DescPropostaVariante = proc_view.DescPropostaVariante,
                DescAbertoFechadoAoMercado = proc_view.DescAbertoFechadoAoMercado,
                DescFornecedorExclusivo = proc_view.DescFornecedorExclusivo,
                CritérioEscolhaProcedimento = proc_view.CriterioEscolhaProcedimento,
                DescEscolhaProcedimento = proc_view.DescEscolhaProcedimento,
                Júri = proc_view.Juri,
                ObjetoDoContrato = proc_view.ObjetoDoContrato,
                PréÁrea = proc_view.PreArea,
                SubmeterPréÁrea = proc_view.SubmeterPreArea,
                ValorDecisãoContratar = proc_view.ValorDecisaoContratar,
                ValorAdjudicaçãoAnteriro = proc_view.ValorAdjudicacaoAnteriro,
                ValorAdjudicaçãoAtual = proc_view.ValorAdjudicacaoAtual,
                DiferençaEuros = proc_view.DiferencaEuros,
                DiferençaPercent = proc_view.DiferencaPercent,
                WorkflowFinanceiros = proc_view.WorkflowFinanceiros,
                WorkflowJurídicos = proc_view.WorkflowJuridicos,
                WorkflowFinanceirosConfirm = proc_view.WorkflowFinanceirosConfirm,
                WorkflowJurídicosConfirm = proc_view.WorkflowJuridicosConfirm,
                AutorizaçãoImobCa = proc_view.AutorizacaoImobCa,
                AutorizaçãoAberturaCa = proc_view.AutorizacaoAberturaCa,
                AutorizaçãoAquisiçãoCa = proc_view.AutorizacaoAquisicaoCa,
                RejeiçãoImobCa = proc_view.RejeicaoImobCa,
                RejeiçãoAberturaCa = proc_view.RejeicaoAberturaCa,
                RejeiçãoAquisiçãoCa = proc_view.RejeicaoAquisicaoCa,
                DataAutorizaçãoImobCa = proc_view.DataAutorizacaoImobCa,
                DataAutorizaçãoAbertCa = proc_view.DataAutorizacaoAbertCa,
                DataAutorizaçãoAquisiCa = proc_view.DataAutorizacaoAquisiCa,
                RatificarCaAbertura = proc_view.RatificarCaAbertura,
                RatificarCaAdjudicação = proc_view.RatificarCaAdjudicacao,
                CaRatificar = proc_view.CaRatificar,
                CaDataRatificaçãoAbert = proc_view.CaDataRatificacaoAbert,
                CaDataRatificaçãoAdjudic = proc_view.CaDataRatificacaoAdjudic,
                NºAta = proc_view.No_Ata,
                DataAta = proc_view.DataAta,
                ComentárioPublicação = proc_view.ComentarioPublicacao,
                DataPublicação = proc_view.DataPublicacao,
                UtilizadorPublicação = proc_view.UtilizadorPublicacao,
                DataSistemaPublicação = proc_view.DataSistemaPublicacao,
                RecolhaComentário = proc_view.RecolhaComentario,
                DataRecolha = proc_view.DataRecolha,
                UtilizadorRecolha = proc_view.UtilizadorRecolha,
                DataSistemaRecolha = proc_view.DataSistemaRecolha,
                ComentárioRelatórioPreliminar = proc_view.ComentarioRelatorioPreliminar,
                DataValidRelatórioPreliminar = proc_view.DataValidRelatorioPreliminar,
                UtilizadorValidRelatórioPreliminar = proc_view.UtilizadorValidRelatorioPreliminar,
                DataSistemaValidRelatórioPreliminar = proc_view.DataSistemaValidRelatorioPreliminar,
                ComentárioAudiênciaPrévia = proc_view.ComentarioAudienciaPrevia,
                DataAudiênciaPrévia = proc_view.DataAudienciaPrevia,
                UtilizadorAudiênciaPrévia = proc_view.UtilizadorAudienciaPrevia,
                DataSistemaAudiênciaPrévia = proc_view.DataSistemaAudienciaPrevia,
                ComentárioRelatórioFinal = proc_view.ComentarioRelatorioFinal,
                DataRelatórioFinal = proc_view.DataRelatorioFinal,
                UtilizadorRelatórioFinal = proc_view.UtilizadorRelatorioFinal,
                DataSistemaRelatórioFinal = proc_view.DataSistemaRelatorioFinal,
                ComentárioNotificação = proc_view.ComentarioNotificacao,
                DataNotificação = proc_view.DataNotificacao,
                UtilizadorNotificação = proc_view.UtilizadorNotificacao,
                DataSistemaNotificação = proc_view.DataSistemaNotificacao,
                PrazoNotificaçãoDias = proc_view.PrazoNotificacaoDias,
                PercentExecução = proc_view.PercentExecucao,
                Arquivado = proc_view.Arquivado,
                DataFechoInicial = proc_view.DataFechoInicial,
                DataFechoPrevista = proc_view.DataFechoPrevista,
                NºDiasProcesso = proc_view.No_DiasProcesso,
                NºDiasAtraso = proc_view.No_DiasAtraso,
                Tratado = proc_view.Tratado,
                Fornecedor = proc_view.Fornecedor,
                Comentário = proc_view.Comentario,
                CaSuspenso = proc_view.CaSuspenso,
                CríticoAbertura = proc_view.CriticoAbertura,
                CríticoAdjudicação = proc_view.CriticoAdjudicacao,
                ObjetoDecisão = proc_view.ObjetoDecisao,
                RazãoNecessidade = proc_view.RazaoNecessidade,
                ProtocoloContrato = proc_view.ProtocoloContrato,
                AutorizaçãoAdjudicação = proc_view.AutorizacaoAdjudicacao,
                NãoAdjudicaçãoEEncerramento = proc_view.NaoAdjudicacaoEEncerramento,
                NãoAdjudicaçãoESuspensão = proc_view.NaoAdjudicacaoESuspensao,
                DataHoraCriação = proc_view.DataHoraCriacao,
                UtilizadorCriação = proc_view.UtilizadorCriacao,
                DataHoraModificação = proc_view.DataHoraModificacao,
                UtilizadorModificação = proc_view.UtilizadorModificacao

            });
        }

        public static RegistoActasView CastRegistoActasToRegistoActasView(RegistoDeAtas reg)
        {
            return (new RegistoActasView
            {
                NumProcedimento = reg.NºProcedimento,
                NumActa = reg.NºAta,
                DataDaActa = reg.DataDaAta,
                Observacoes = reg.Observações,
                DataHoraCriacao = reg.DataHoraCriação,
                UtilizadorCriacao = reg.UtilizadorCriação,
                DataHoraModificacao = reg.DataHoraModificação,
                UtilizadorModificacao = reg.UtilizadorModificação
            });
        }

        public static RegistoDeAtas CastRegistoActasViewToRegistoActas(RegistoActasView reg)
        {
            return (new RegistoDeAtas
            {
                NºProcedimento = reg.NumProcedimento,
                NºAta = reg.NumActa,
                DataDaAta = reg.DataDaActa,
                Observações = reg.Observacoes,
                DataHoraCriação = reg.DataHoraCriacao,
                UtilizadorCriação = reg.UtilizadorCriacao,
                DataHoraModificação = reg.DataHoraModificacao,
                UtilizadorModificação = reg.UtilizadorModificacao
            });
        }

        public static TemposPACCPView CastTemposPaCcpToTemposCCPView(TemposPaCcp temp)
        {
            return (new TemposPACCPView()
            {
                NumProcedimento = temp.NºProcedimento,
                Estado0 = temp.Estado0,
                Estado1 = temp.Estado1,
                Estado2 = temp.Estado2,
                Estado3 = temp.Estado3,
                Estado4 = temp.Estado4,
                Estado5 = temp.Estado5,
                Estado6 = temp.Estado6,
                Estado7 = temp.Estado7,
                Estado8 = temp.Estado8,
                Estado9 = temp.Estado9,
                Estado10 = temp.Estado10,
                Estado11 = temp.Estado11,
                Estado12 = temp.Estado12,
                Estado13 = temp.Estado13,
                Estado14 = temp.Estado14,
                Estado15 = temp.Estado15,
                Estado16 = temp.Estado16,
                Estado17 = temp.Estado17,
                Estado18 = temp.Estado18,
                Estado19 = temp.Estado19,
                Estado20 = temp.Estado20,
                Estado0Tg = temp.Estado0Tg,
                Estado1Tg = temp.Estado1Tg,
                Estado2Tg = temp.Estado2Tg,
                Estado3Tg = temp.Estado3Tg,
                Estado4Tg = temp.Estado4Tg,
                Estado5Tg = temp.Estado5Tg,
                Estado6Tg = temp.Estado6Tg,
                Estado7Tg = temp.Estado7Tg,
                Estado8Tg = temp.Estado8Tg,
                Estado9Tg = temp.Estado9Tg,
                Estado10Tg = temp.Estado10Tg,
                Estado11Tg = temp.Estado11Tg,
                Estado12Tg = temp.Estado12Tg,
                Estado13Tg = temp.Estado13Tg,
                Estado14Tg = temp.Estado14Tg,
                Estado15Tg = temp.Estado15Tg,
                Estado16Tg = temp.Estado16Tg,
                Estado17Tg = temp.Estado17Tg,
                Estado18Tg = temp.Estado18Tg,
                Estado19Tg = temp.Estado19Tg,
                Estado20Tg = temp.Estado20Tg,
                DataHoraCriacao = temp.DataHoraCriação,
                UtilizadorCriacao = temp.UtilizadorCriação,
                DataHoraModificacao = temp.DataHoraModificação,
                UtilizadorModificacao = temp.UtilizadorModificação
            });
        }

        public static TemposPaCcp CastTemposCCPViewToTemposPaCcp(TemposPACCPView temp_view)
        {
            return (new TemposPaCcp()
            {
                NºProcedimento = temp_view.NumProcedimento,
                Estado0 = temp_view.Estado0,
                Estado1 = temp_view.Estado1,
                Estado2 = temp_view.Estado2,
                Estado3 = temp_view.Estado3,
                Estado4 = temp_view.Estado4,
                Estado5 = temp_view.Estado5,
                Estado6 = temp_view.Estado6,
                Estado7 = temp_view.Estado7,
                Estado8 = temp_view.Estado8,
                Estado9 = temp_view.Estado9,
                Estado10 = temp_view.Estado10,
                Estado11 = temp_view.Estado11,
                Estado12 = temp_view.Estado12,
                Estado13 = temp_view.Estado13,
                Estado14 = temp_view.Estado14,
                Estado15 = temp_view.Estado15,
                Estado16 = temp_view.Estado16,
                Estado17 = temp_view.Estado17,
                Estado18 = temp_view.Estado18,
                Estado19 = temp_view.Estado19,
                Estado20 = temp_view.Estado20,
                Estado0Tg = temp_view.Estado0Tg,
                Estado1Tg = temp_view.Estado1Tg,
                Estado2Tg = temp_view.Estado2Tg,
                Estado3Tg = temp_view.Estado3Tg,
                Estado4Tg = temp_view.Estado4Tg,
                Estado5Tg = temp_view.Estado5Tg,
                Estado6Tg = temp_view.Estado6Tg,
                Estado7Tg = temp_view.Estado7Tg,
                Estado8Tg = temp_view.Estado8Tg,
                Estado9Tg = temp_view.Estado9Tg,
                Estado10Tg = temp_view.Estado10Tg,
                Estado11Tg = temp_view.Estado11Tg,
                Estado12Tg = temp_view.Estado12Tg,
                Estado13Tg = temp_view.Estado13Tg,
                Estado14Tg = temp_view.Estado14Tg,
                Estado15Tg = temp_view.Estado15Tg,
                Estado16Tg = temp_view.Estado16Tg,
                Estado17Tg = temp_view.Estado17Tg,
                Estado18Tg = temp_view.Estado18Tg,
                Estado19Tg = temp_view.Estado19Tg,
                Estado20Tg = temp_view.Estado20Tg,
                DataHoraCriação = temp_view.DataHoraCriacao,
                UtilizadorCriação = temp_view.UtilizadorCriacao,
                DataHoraModificação = temp_view.DataHoraModificacao,
                UtilizadorModificação = temp_view.UtilizadorModificacao
            });
        }
        #endregion
    }
}
