//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSSuchNav2017
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", ConfigurationName="WSSuchNav2017.WSNAV2017_Port")]
    public interface WSNAV2017_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017:FxValidaDimensoes", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSuchNav2017.FxValidaDimensoes_Result> FxValidaDimensoesAsync(WSSuchNav2017.FxValidaDimensoes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017:WSNovaGuiaTransporte", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSuchNav2017.WSNovaGuiaTransporte_Result> WSNovaGuiaTransporteAsync(WSSuchNav2017.WSNovaGuiaTransporte request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017:WSRegistaGuia", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSuchNav2017.WSRegistaGuia_Result> WSRegistaGuiaAsync(WSSuchNav2017.WSRegistaGuia request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017:WSForcaRegistoGuia", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSuchNav2017.WSForcaRegistoGuia_Result> WSForcaRegistoGuiaAsync(WSSuchNav2017.WSForcaRegistoGuia request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017:WSgetNumPreRegisto", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSuchNav2017.WSgetNumPreRegisto_Result> WSgetNumPreRegistoAsync(WSSuchNav2017.WSgetNumPreRegisto request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FxValidaDimensoes", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class FxValidaDimensoes
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string pRegiao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=1)]
        public string pArea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=2)]
        public string pCResp;
        
        public FxValidaDimensoes()
        {
        }
        
        public FxValidaDimensoes(string pRegiao, string pArea, string pCResp)
        {
            this.pRegiao = pRegiao;
            this.pArea = pArea;
            this.pCResp = pCResp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FxValidaDimensoes_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class FxValidaDimensoes_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string return_value;
        
        public FxValidaDimensoes_Result()
        {
        }
        
        public FxValidaDimensoes_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSNovaGuiaTransporte", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSNovaGuiaTransporte
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string idUtilizador;
        
        public WSNovaGuiaTransporte()
        {
        }
        
        public WSNovaGuiaTransporte(string idUtilizador)
        {
            this.idUtilizador = idUtilizador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSNovaGuiaTransporte_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSNovaGuiaTransporte_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string return_value;
        
        public WSNovaGuiaTransporte_Result()
        {
        }
        
        public WSNovaGuiaTransporte_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSRegistaGuia", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSRegistaGuia
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string noGuiaTransporte;
        
        public WSRegistaGuia()
        {
        }
        
        public WSRegistaGuia(string noGuiaTransporte)
        {
            this.noGuiaTransporte = noGuiaTransporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSRegistaGuia_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSRegistaGuia_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string return_value;
        
        public WSRegistaGuia_Result()
        {
        }
        
        public WSRegistaGuia_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSForcaRegistoGuia", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSForcaRegistoGuia
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string noGuiaTransporteHistorico;
        
        public WSForcaRegistoGuia()
        {
        }
        
        public WSForcaRegistoGuia(string noGuiaTransporteHistorico)
        {
            this.noGuiaTransporteHistorico = noGuiaTransporteHistorico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSForcaRegistoGuia_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSForcaRegistoGuia_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string return_value;
        
        public WSForcaRegistoGuia_Result()
        {
        }
        
        public WSForcaRegistoGuia_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSgetNumPreRegisto", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSgetNumPreRegisto
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string pProjeto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=1)]
        public int pGrupoFatura;
        
        public WSgetNumPreRegisto()
        {
        }
        
        public WSgetNumPreRegisto(string pProjeto, int pGrupoFatura)
        {
            this.pProjeto = pProjeto;
            this.pGrupoFatura = pGrupoFatura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WSgetNumPreRegisto_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", IsWrapped=true)]
    public partial class WSgetNumPreRegisto_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSNAV2017", Order=0)]
        public string return_value;
        
        public WSgetNumPreRegisto_Result()
        {
        }
        
        public WSgetNumPreRegisto_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface WSNAV2017_PortChannel : WSSuchNav2017.WSNAV2017_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class WSNAV2017_PortClient : System.ServiceModel.ClientBase<WSSuchNav2017.WSNAV2017_Port>, WSSuchNav2017.WSNAV2017_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSNAV2017_PortClient() : 
                base(WSNAV2017_PortClient.GetDefaultBinding(), WSNAV2017_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSNAV2017_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSNAV2017_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(WSNAV2017_PortClient.GetBindingForEndpoint(endpointConfiguration), WSNAV2017_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSNAV2017_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSNAV2017_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSNAV2017_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSNAV2017_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSNAV2017_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSuchNav2017.FxValidaDimensoes_Result> WSSuchNav2017.WSNAV2017_Port.FxValidaDimensoesAsync(WSSuchNav2017.FxValidaDimensoes request)
        {
            return base.Channel.FxValidaDimensoesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSuchNav2017.FxValidaDimensoes_Result> FxValidaDimensoesAsync(string pRegiao, string pArea, string pCResp)
        {
            WSSuchNav2017.FxValidaDimensoes inValue = new WSSuchNav2017.FxValidaDimensoes();
            inValue.pRegiao = pRegiao;
            inValue.pArea = pArea;
            inValue.pCResp = pCResp;
            return ((WSSuchNav2017.WSNAV2017_Port)(this)).FxValidaDimensoesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSuchNav2017.WSNovaGuiaTransporte_Result> WSSuchNav2017.WSNAV2017_Port.WSNovaGuiaTransporteAsync(WSSuchNav2017.WSNovaGuiaTransporte request)
        {
            return base.Channel.WSNovaGuiaTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSuchNav2017.WSNovaGuiaTransporte_Result> WSNovaGuiaTransporteAsync(string idUtilizador)
        {
            WSSuchNav2017.WSNovaGuiaTransporte inValue = new WSSuchNav2017.WSNovaGuiaTransporte();
            inValue.idUtilizador = idUtilizador;
            return ((WSSuchNav2017.WSNAV2017_Port)(this)).WSNovaGuiaTransporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSuchNav2017.WSRegistaGuia_Result> WSSuchNav2017.WSNAV2017_Port.WSRegistaGuiaAsync(WSSuchNav2017.WSRegistaGuia request)
        {
            return base.Channel.WSRegistaGuiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSuchNav2017.WSRegistaGuia_Result> WSRegistaGuiaAsync(string noGuiaTransporte)
        {
            WSSuchNav2017.WSRegistaGuia inValue = new WSSuchNav2017.WSRegistaGuia();
            inValue.noGuiaTransporte = noGuiaTransporte;
            return ((WSSuchNav2017.WSNAV2017_Port)(this)).WSRegistaGuiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSuchNav2017.WSForcaRegistoGuia_Result> WSSuchNav2017.WSNAV2017_Port.WSForcaRegistoGuiaAsync(WSSuchNav2017.WSForcaRegistoGuia request)
        {
            return base.Channel.WSForcaRegistoGuiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSuchNav2017.WSForcaRegistoGuia_Result> WSForcaRegistoGuiaAsync(string noGuiaTransporteHistorico)
        {
            WSSuchNav2017.WSForcaRegistoGuia inValue = new WSSuchNav2017.WSForcaRegistoGuia();
            inValue.noGuiaTransporteHistorico = noGuiaTransporteHistorico;
            return ((WSSuchNav2017.WSNAV2017_Port)(this)).WSForcaRegistoGuiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSuchNav2017.WSgetNumPreRegisto_Result> WSSuchNav2017.WSNAV2017_Port.WSgetNumPreRegistoAsync(WSSuchNav2017.WSgetNumPreRegisto request)
        {
            return base.Channel.WSgetNumPreRegistoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSuchNav2017.WSgetNumPreRegisto_Result> WSgetNumPreRegistoAsync(string pProjeto, int pGrupoFatura)
        {
            WSSuchNav2017.WSgetNumPreRegisto inValue = new WSSuchNav2017.WSgetNumPreRegisto();
            inValue.pProjeto = pProjeto;
            inValue.pGrupoFatura = pGrupoFatura;
            return ((WSSuchNav2017.WSNAV2017_Port)(this)).WSgetNumPreRegistoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSNAV2017_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSNAV2017_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://10.101.1.13:8047/DynamicsNAV100_QUAL/WS/SUCH - QUALIDADE/Codeunit/WSNAV201" +
                        "7");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSNAV2017_PortClient.GetBindingForEndpoint(EndpointConfiguration.WSNAV2017_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSNAV2017_PortClient.GetEndpointAddress(EndpointConfiguration.WSNAV2017_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            WSNAV2017_Port,
        }
    }
}
