//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCustomerNAV
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", ConfigurationName="WSCustomerNAV.WSCustomer_Port")]
    public interface WSCustomer_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.Read_Result> ReadAsync(WSCustomerNAV.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.ReadByRecId_Result> ReadByRecIdAsync(WSCustomerNAV.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.ReadMultiple_Result> ReadMultipleAsync(WSCustomerNAV.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.IsUpdated_Result> IsUpdatedAsync(WSCustomerNAV.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(WSCustomerNAV.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.Create_Result> CreateAsync(WSCustomerNAV.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.CreateMultiple_Result> CreateMultipleAsync(WSCustomerNAV.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.Update_Result> UpdateAsync(WSCustomerNAV.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.UpdateMultiple_Result> UpdateMultipleAsync(WSCustomerNAV.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/wscustomer:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCustomerNAV.Delete_Result> DeleteAsync(WSCustomerNAV.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public partial class WSCustomer
    {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string search_NameField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string country_Region_CodeField;
        
        private string primary_Contact_NoField;
        
        private string contactNameField;
        
        private string phone_NoField;
        
        private string e_MailField;
        
        private string fax_NoField;
        
        private string home_PageField;
        
        private string language_CodeField;
        
        private string countyField;
        
        private string vAT_Registration_NoField;
        
        private string payment_Terms_CodeField;
        
        private string payment_Method_CodeField;
        
        private string salesperson_CodeField;
        
        private string responsibility_CenterField;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private Regiao_Cliente regiao_ClienteField;
        
        private bool regiao_ClienteFieldSpecified;
        
        private string global_Dimension_1_CodeField;
        
        private string centro_Resp_DimensaoField;
        
        private string currency_CodeField;
        
        private string no_SeriesField;
        
        private Blocked blockedField;
        
        private bool blockedFieldSpecified;
        
        private string bill_to_Customer_NoField;
        
        private string gen_Bus_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string customer_Posting_GroupField;
        
        private string no_Fornecedor_AssocField;
        
        private bool cliente_AssociadoField;
        
        private bool cliente_AssociadoFieldSpecified;
        
        private decimal taxa_AprovisionamentoField;
        
        private bool taxa_AprovisionamentoFieldSpecified;
        
        private bool abrigo_Lei_CompromissoField;
        
        private bool abrigo_Lei_CompromissoFieldSpecified;
        
        private bool cliente_InternoField;
        
        private bool cliente_InternoFieldSpecified;
        
        private bool cliente_NacionalField;
        
        private bool cliente_NacionalFieldSpecified;
        
        private string associado_A_NField;
        
        private Tipo_Cliente tipo_ClienteField;
        
        private bool tipo_ClienteFieldSpecified;
        
        private Natureza_Cliente natureza_ClienteField;
        
        private bool natureza_ClienteFieldSpecified;
        
        private string cliente_PrincipalField;
        
        private System.DateTime data_Cliente_PaiField;
        
        private bool data_Cliente_PaiFieldSpecified;
        
        private string codigo_Serviço_DGOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Search_Name
        {
            get
            {
                return this.search_NameField;
            }
            set
            {
                this.search_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address_2
        {
            get
            {
                return this.address_2Field;
            }
            set
            {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Post_Code
        {
            get
            {
                return this.post_CodeField;
            }
            set
            {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Country_Region_Code
        {
            get
            {
                return this.country_Region_CodeField;
            }
            set
            {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Primary_Contact_No
        {
            get
            {
                return this.primary_Contact_NoField;
            }
            set
            {
                this.primary_Contact_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Phone_No
        {
            get
            {
                return this.phone_NoField;
            }
            set
            {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string E_Mail
        {
            get
            {
                return this.e_MailField;
            }
            set
            {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Fax_No
        {
            get
            {
                return this.fax_NoField;
            }
            set
            {
                this.fax_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Home_Page
        {
            get
            {
                return this.home_PageField;
            }
            set
            {
                this.home_PageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Language_Code
        {
            get
            {
                return this.language_CodeField;
            }
            set
            {
                this.language_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string VAT_Registration_No
        {
            get
            {
                return this.vAT_Registration_NoField;
            }
            set
            {
                this.vAT_Registration_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Payment_Terms_Code
        {
            get
            {
                return this.payment_Terms_CodeField;
            }
            set
            {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Payment_Method_Code
        {
            get
            {
                return this.payment_Method_CodeField;
            }
            set
            {
                this.payment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Salesperson_Code
        {
            get
            {
                return this.salesperson_CodeField;
            }
            set
            {
                this.salesperson_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Responsibility_Center
        {
            get
            {
                return this.responsibility_CenterField;
            }
            set
            {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=22)]
        public System.DateTime Last_Date_Modified
        {
            get
            {
                return this.last_Date_ModifiedField;
            }
            set
            {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified
        {
            get
            {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set
            {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public Regiao_Cliente Regiao_Cliente
        {
            get
            {
                return this.regiao_ClienteField;
            }
            set
            {
                this.regiao_ClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Regiao_ClienteSpecified
        {
            get
            {
                return this.regiao_ClienteFieldSpecified;
            }
            set
            {
                this.regiao_ClienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Global_Dimension_1_Code
        {
            get
            {
                return this.global_Dimension_1_CodeField;
            }
            set
            {
                this.global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Centro_Resp_Dimensao
        {
            get
            {
                return this.centro_Resp_DimensaoField;
            }
            set
            {
                this.centro_Resp_DimensaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Currency_Code
        {
            get
            {
                return this.currency_CodeField;
            }
            set
            {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string No_Series
        {
            get
            {
                return this.no_SeriesField;
            }
            set
            {
                this.no_SeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public Blocked Blocked
        {
            get
            {
                return this.blockedField;
            }
            set
            {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified
        {
            get
            {
                return this.blockedFieldSpecified;
            }
            set
            {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Bill_to_Customer_No
        {
            get
            {
                return this.bill_to_Customer_NoField;
            }
            set
            {
                this.bill_to_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Gen_Bus_Posting_Group
        {
            get
            {
                return this.gen_Bus_Posting_GroupField;
            }
            set
            {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string VAT_Bus_Posting_Group
        {
            get
            {
                return this.vAT_Bus_Posting_GroupField;
            }
            set
            {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Customer_Posting_Group
        {
            get
            {
                return this.customer_Posting_GroupField;
            }
            set
            {
                this.customer_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string No_Fornecedor_Assoc
        {
            get
            {
                return this.no_Fornecedor_AssocField;
            }
            set
            {
                this.no_Fornecedor_AssocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool Cliente_Associado
        {
            get
            {
                return this.cliente_AssociadoField;
            }
            set
            {
                this.cliente_AssociadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cliente_AssociadoSpecified
        {
            get
            {
                return this.cliente_AssociadoFieldSpecified;
            }
            set
            {
                this.cliente_AssociadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public decimal Taxa_Aprovisionamento
        {
            get
            {
                return this.taxa_AprovisionamentoField;
            }
            set
            {
                this.taxa_AprovisionamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Taxa_AprovisionamentoSpecified
        {
            get
            {
                return this.taxa_AprovisionamentoFieldSpecified;
            }
            set
            {
                this.taxa_AprovisionamentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool Abrigo_Lei_Compromisso
        {
            get
            {
                return this.abrigo_Lei_CompromissoField;
            }
            set
            {
                this.abrigo_Lei_CompromissoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Abrigo_Lei_CompromissoSpecified
        {
            get
            {
                return this.abrigo_Lei_CompromissoFieldSpecified;
            }
            set
            {
                this.abrigo_Lei_CompromissoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool Cliente_Interno
        {
            get
            {
                return this.cliente_InternoField;
            }
            set
            {
                this.cliente_InternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cliente_InternoSpecified
        {
            get
            {
                return this.cliente_InternoFieldSpecified;
            }
            set
            {
                this.cliente_InternoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool Cliente_Nacional
        {
            get
            {
                return this.cliente_NacionalField;
            }
            set
            {
                this.cliente_NacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cliente_NacionalSpecified
        {
            get
            {
                return this.cliente_NacionalFieldSpecified;
            }
            set
            {
                this.cliente_NacionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Associado_A_N
        {
            get
            {
                return this.associado_A_NField;
            }
            set
            {
                this.associado_A_NField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public Tipo_Cliente Tipo_Cliente
        {
            get
            {
                return this.tipo_ClienteField;
            }
            set
            {
                this.tipo_ClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tipo_ClienteSpecified
        {
            get
            {
                return this.tipo_ClienteFieldSpecified;
            }
            set
            {
                this.tipo_ClienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public Natureza_Cliente Natureza_Cliente
        {
            get
            {
                return this.natureza_ClienteField;
            }
            set
            {
                this.natureza_ClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Natureza_ClienteSpecified
        {
            get
            {
                return this.natureza_ClienteFieldSpecified;
            }
            set
            {
                this.natureza_ClienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Cliente_Principal
        {
            get
            {
                return this.cliente_PrincipalField;
            }
            set
            {
                this.cliente_PrincipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=43)]
        public System.DateTime Data_Cliente_Pai
        {
            get
            {
                return this.data_Cliente_PaiField;
            }
            set
            {
                this.data_Cliente_PaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Data_Cliente_PaiSpecified
        {
            get
            {
                return this.data_Cliente_PaiFieldSpecified;
            }
            set
            {
                this.data_Cliente_PaiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string Codigo_Serviço_DGO
        {
            get
            {
                return this.codigo_Serviço_DGOField;
            }
            set
            {
                this.codigo_Serviço_DGOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public enum Regiao_Cliente
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Norte,
        
        /// <remarks/>
        Centro,
        
        /// <remarks/>
        Sul,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public enum Blocked
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Ship,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public enum Tipo_Cliente
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public enum Natureza_Cliente
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Cliente_Estado_do_SNS,
        
        /// <remarks/>
        Cliente_Estado_excepto_SNS,
        
        /// <remarks/>
        Cliente_Externo_ao_Estado,
        
        /// <remarks/>
        Cliente_Interno,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public partial class WSCustomer_Filter
    {
        
        private WSCustomer_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WSCustomer_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer")]
    public enum WSCustomer_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        Primary_Contact_No,
        
        /// <remarks/>
        ContactName,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        Home_Page,
        
        /// <remarks/>
        Language_Code,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        VAT_Registration_No,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Payment_Method_Code,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Regiao_Cliente,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Centro_Resp_Dimensao,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        No_Series,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Bill_to_Customer_No,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Customer_Posting_Group,
        
        /// <remarks/>
        No_Fornecedor_Assoc,
        
        /// <remarks/>
        Cliente_Associado,
        
        /// <remarks/>
        Taxa_Aprovisionamento,
        
        /// <remarks/>
        Abrigo_Lei_Compromisso,
        
        /// <remarks/>
        Cliente_Interno,
        
        /// <remarks/>
        Cliente_Nacional,
        
        /// <remarks/>
        Associado_A_N,
        
        /// <remarks/>
        Tipo_Cliente,
        
        /// <remarks/>
        Natureza_Cliente,
        
        /// <remarks/>
        Cliente_Principal,
        
        /// <remarks/>
        Data_Cliente_Pai,
        
        /// <remarks/>
        Codigo_Serviço_DGO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public WSCustomerNAV.WSCustomer WSCustomer;
        
        public Read_Result()
        {
        }
        
        public Read_Result(WSCustomerNAV.WSCustomer WSCustomer)
        {
            this.WSCustomer = WSCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public WSCustomerNAV.WSCustomer WSCustomer;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(WSCustomerNAV.WSCustomer WSCustomer)
        {
            this.WSCustomer = WSCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public WSCustomerNAV.WSCustomer_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(WSCustomerNAV.WSCustomer_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSCustomerNAV.WSCustomer[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(WSCustomerNAV.WSCustomer[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public WSCustomerNAV.WSCustomer WSCustomer;
        
        public Create()
        {
        }
        
        public Create(WSCustomerNAV.WSCustomer WSCustomer)
        {
            this.WSCustomer = WSCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public WSCustomerNAV.WSCustomer WSCustomer;
        
        public Create_Result()
        {
        }
        
        public Create_Result(WSCustomerNAV.WSCustomer WSCustomer)
        {
            this.WSCustomer = WSCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSCustomerNAV.WSCustomer[] WSCustomer_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(WSCustomerNAV.WSCustomer[] WSCustomer_List)
        {
            this.WSCustomer_List = WSCustomer_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSCustomerNAV.WSCustomer[] WSCustomer_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(WSCustomerNAV.WSCustomer[] WSCustomer_List)
        {
            this.WSCustomer_List = WSCustomer_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public WSCustomerNAV.WSCustomer WSCustomer;
        
        public Update()
        {
        }
        
        public Update(WSCustomerNAV.WSCustomer WSCustomer)
        {
            this.WSCustomer = WSCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public WSCustomerNAV.WSCustomer WSCustomer;
        
        public Update_Result()
        {
        }
        
        public Update_Result(WSCustomerNAV.WSCustomer WSCustomer)
        {
            this.WSCustomer = WSCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSCustomerNAV.WSCustomer[] WSCustomer_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(WSCustomerNAV.WSCustomer[] WSCustomer_List)
        {
            this.WSCustomer_List = WSCustomer_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WSCustomerNAV.WSCustomer[] WSCustomer_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(WSCustomerNAV.WSCustomer[] WSCustomer_List)
        {
            this.WSCustomer_List = WSCustomer_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/wscustomer", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/wscustomer", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface WSCustomer_PortChannel : WSCustomerNAV.WSCustomer_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class WSCustomer_PortClient : System.ServiceModel.ClientBase<WSCustomerNAV.WSCustomer_Port>, WSCustomerNAV.WSCustomer_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSCustomer_PortClient() : 
                base(WSCustomer_PortClient.GetDefaultBinding(), WSCustomer_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSCustomer_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomer_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(WSCustomer_PortClient.GetBindingForEndpoint(endpointConfiguration), WSCustomer_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomer_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSCustomer_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomer_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSCustomer_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomer_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCustomerNAV.Read_Result> WSCustomerNAV.WSCustomer_Port.ReadAsync(WSCustomerNAV.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.Read_Result> ReadAsync(string No)
        {
            WSCustomerNAV.Read inValue = new WSCustomerNAV.Read();
            inValue.No = No;
            return ((WSCustomerNAV.WSCustomer_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCustomerNAV.ReadByRecId_Result> WSCustomerNAV.WSCustomer_Port.ReadByRecIdAsync(WSCustomerNAV.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            WSCustomerNAV.ReadByRecId inValue = new WSCustomerNAV.ReadByRecId();
            inValue.recId = recId;
            return ((WSCustomerNAV.WSCustomer_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCustomerNAV.ReadMultiple_Result> WSCustomerNAV.WSCustomer_Port.ReadMultipleAsync(WSCustomerNAV.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.ReadMultiple_Result> ReadMultipleAsync(WSCustomerNAV.WSCustomer_Filter[] filter, string bookmarkKey, int setSize)
        {
            WSCustomerNAV.ReadMultiple inValue = new WSCustomerNAV.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((WSCustomerNAV.WSCustomer_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCustomerNAV.IsUpdated_Result> WSCustomerNAV.WSCustomer_Port.IsUpdatedAsync(WSCustomerNAV.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            WSCustomerNAV.IsUpdated inValue = new WSCustomerNAV.IsUpdated();
            inValue.Key = Key;
            return ((WSCustomerNAV.WSCustomer_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCustomerNAV.GetRecIdFromKey_Result> WSCustomerNAV.WSCustomer_Port.GetRecIdFromKeyAsync(WSCustomerNAV.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            WSCustomerNAV.GetRecIdFromKey inValue = new WSCustomerNAV.GetRecIdFromKey();
            inValue.Key = Key;
            return ((WSCustomerNAV.WSCustomer_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.Create_Result> CreateAsync(WSCustomerNAV.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.CreateMultiple_Result> CreateMultipleAsync(WSCustomerNAV.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.Update_Result> UpdateAsync(WSCustomerNAV.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.UpdateMultiple_Result> UpdateMultipleAsync(WSCustomerNAV.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCustomerNAV.Delete_Result> WSCustomerNAV.WSCustomer_Port.DeleteAsync(WSCustomerNAV.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCustomerNAV.Delete_Result> DeleteAsync(string Key)
        {
            WSCustomerNAV.Delete inValue = new WSCustomerNAV.Delete();
            inValue.Key = Key;
            return ((WSCustomerNAV.WSCustomer_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSCustomer_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSCustomer_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://such-navdev.such.local:8047/DynamicsNAV100_QUAL/WS/SUCH - QUALIDADE/Page/W" +
                        "SCustomer");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSCustomer_PortClient.GetBindingForEndpoint(EndpointConfiguration.WSCustomer_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSCustomer_PortClient.GetEndpointAddress(EndpointConfiguration.WSCustomer_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            WSCustomer_Port,
        }
    }
}
