using System;
using System.Collections.Generic;

namespace Hydra.Such.Data.Evolution.DatabaseReference
{
    public partial class Orcamento
    {
        public byte[] Timestamp { get; set; }
        public int DocumentType { get; set; }
        public string No { get; set; }
        public string Description { get; set; }
        public int? ObjectRefType { get; set; }
        public string ObjectRefNo { get; set; }
        public string ObjectRefDescription { get; set; }
        public string ComponentOf { get; set; }
        public string OrderType { get; set; }
        public string MaintenanceActivity { get; set; }
        public int? SourceDocType { get; set; }
        public string SourceDocNo { get; set; }
        public string ContractNo { get; set; }
        public int? Priority { get; set; }
        public int? Status { get; set; }
        public string SuspendedOrderReason { get; set; }
        public string ResponsibilityCenter { get; set; }
        public DateTime? LastDateModified { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerPostCode { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string CustomerEMail { get; set; }
        public string CustomerShipToCode { get; set; }
        public string CustomerFaxNo { get; set; }
        public string CustomerReference { get; set; }
        public string CustomerContactName { get; set; }
        public string CustomerCountryCode { get; set; }
        public DateTime? PostingDate { get; set; }
        public string CustomerCounty { get; set; }
        public string JobNo { get; set; }
        public int? ApplicationMethod { get; set; }
        public string LanguageCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string RespCenterCountryCode { get; set; }
        public decimal? TotalQuantity { get; set; }
        public decimal? TotalQtyToInvoice { get; set; }
        public string RespCenterName { get; set; }
        public string RespCenterName2 { get; set; }
        public string RespCenterFaxNo { get; set; }
        public string RespCenterCounty { get; set; }
        public string RespCenterAddress { get; set; }
        public string RespCenterAddress2 { get; set; }
        public string RespCenterPostCode { get; set; }
        public string RespCenterCity { get; set; }
        public string RespCenterContact { get; set; }
        public string RespCenterPhoneNo { get; set; }
        public string RespCenterReference { get; set; }
        public string FaNo { get; set; }
        public string FlNo { get; set; }
        public string FlDescription { get; set; }
        public string ResponsibleEmployee { get; set; }
        public string EnteredBy { get; set; }
        public string MaintenanceResponsible { get; set; }
        public string PlannerGroupNo { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? OrderTime { get; set; }
        public DateTime? DocumentDate { get; set; }
        public DateTime? ExpectedFinishingDate { get; set; }
        public DateTime? ExpectedFinishingTime { get; set; }
        public DateTime? ExpectedStartingDate { get; set; }
        public DateTime? ExpectedStartingTime { get; set; }
        public DateTime? StartingDate { get; set; }
        public DateTime? StartingTime { get; set; }
        public decimal? ResponseTimeHours { get; set; }
        public decimal? MaintenanceTimeHours { get; set; }
        public DateTime? FinishingDate { get; set; }
        public DateTime? FinishingTime { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string CustomerPriceGroup { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string VatRegistrationNo { get; set; }
        public string PurchaserCode { get; set; }
        public string PlannedOrderNo { get; set; }
        public string NoSeries { get; set; }
        public int? Reserve { get; set; }
        public string Validade { get; set; }
        public byte? Budget { get; set; }
        public string FaPostingGroup { get; set; }
        public string WorkCenterNo { get; set; }
        public string MachineCenterNo { get; set; }
        public decimal? FinishingTimeHours { get; set; }
        public string TipoContactoCliente { get; set; }
        public string CustomerDocNo { get; set; }
        public string JobPostingGroup { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToName { get; set; }
        public string ShipToName2 { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToPostCode { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToContact { get; set; }
        public string ShortcutDimension3Code { get; set; }
        public string ShortcutDimension4Code { get; set; }
        public DateTime? DataFecho { get; set; }
        public DateTime? HoraFecho { get; set; }
        public string Loc1 { get; set; }
        public int? EstadoOrcamento { get; set; }
        public string NumOrdem { get; set; }
        public string NoDocumentoEnviado { get; set; }
        public string FormaDeEnvio { get; set; }
        public DateTime? DataDeEnvio { get; set; }
        public DateTime? DataEntrada { get; set; }
        public string NºGeste { get; set; }
        public DateTime? DataEntrega { get; set; }
        public DateTime? DataSaída { get; set; }
        public int? OrigemOrdem { get; set; }
        public string Loc2 { get; set; }
        public string Loc3 { get; set; }
        public int? Urgência { get; set; }
        public int? PrioridadeObra { get; set; }
        public byte? FechoTécnicoObra { get; set; }
        public string PrazoDeExecuçãoDaOrdem { get; set; }
        public string Descrição1 { get; set; }
        public string Descrição2 { get; set; }
        public string Descrição3 { get; set; }
        public decimal? ValorTotalPrev { get; set; }
        public decimal? TotalQPrev { get; set; }
        public decimal? TotalQReal { get; set; }
        public int? NºLinhaContrato { get; set; }
        public DateTime? DataReabertura { get; set; }
        public DateTime? HoraReabertura { get; set; }
        public string NºAntigoAs400 { get; set; }
        public decimal? ValorFacturado { get; set; }
        public string ObjectoManutençãoAs400 { get; set; }
        public decimal? TotalQuantidadeReal { get; set; }
        public decimal? ValorCustoRealTotal { get; set; }
        public string ClienteContrato { get; set; }
        public decimal? TotalQuantidadeFact { get; set; }
        public decimal? TotalValorFact { get; set; }
        public decimal? PMargem { get; set; }
        public decimal? Margem { get; set; }
        public string FTextDescDim1 { get; set; }
        public string Cc { get; set; }
        public string Paginas { get; set; }
        public string De { get; set; }
        public string Compensa { get; set; }
        public string NãoCompensa { get; set; }
        public byte? ObraReclamada { get; set; }
        public int? NºReclamacao { get; set; }
        public string DescricaoReclamacao { get; set; }
        public DateTime? DataPedidoReparação { get; set; }
        public DateTime? HoraPedidoReparação { get; set; }
        public string FechadoPor { get; set; }
        public string ReabertoPor { get; set; }
        public string Dimension2CodeOld { get; set; }
        public byte? MensagemImpressoOrdem { get; set; }
        public string NovaReconv { get; set; }
        public string ObjectoServiço { get; set; }
        public DateTime? DataPedido { get; set; }
        public DateTime? DataValidade { get; set; }
        public DateTime? ValidadePedido { get; set; }
        public decimal? ValorProjecto { get; set; }
        public string DeliberaçãoCa { get; set; }
        public byte? ServInternosRequisições { get; set; }
        public byte? ServInternosFolhasDeObra { get; set; }
        public byte? ServInternosDébInternos { get; set; }
        public byte? MãoDeObraEDeslocações { get; set; }
        public string ConfigResponsavel { get; set; }
        public DateTime? DataUltimoMail { get; set; }
        public string UserChefeProjecto { get; set; }
        public DateTime? DataChefeProjecto { get; set; }
        public string UserResponsavel { get; set; }
        public DateTime? DataResponsavel { get; set; }
        public DateTime? DataFacturação { get; set; }
        public string TécnicoExecutante { get; set; }
        public string NoCompromisso { get; set; }
        public string NoDocumentoContactoInicial { get; set; }
        public string TipoContactoClienteInicial { get; set; }
        public string LocalAec { get; set; }
        public int? Contrato { get; set; }
        public int? IdClienteEvolution { get; set; }
        public int? IdInstituicaoEvolution { get; set; }
        public int? IdServicoEvolution { get; set; }
        public int? IdTecnico1 { get; set; }
        public int? IdTecnico2 { get; set; }
        public int? IdTecnico3 { get; set; }
        public int? IdTecnico4 { get; set; }
        public int? IdTecnico5 { get; set; }
        public int OrcAlternativo { get; set; }
        public string ReferenciaEncomenda { get; set; }
    }
}
