using System;
using System.Collections.Generic;
using System.Text;

namespace Hydra.Such.Data.ViewModel
{
    public class NAVSalesHeaderViewModel : ErrorHandler
    {       
        public int DocumentType { get; set; }
        public string No { get; set; }
        public string Sell_toCustomerNo { get; set; }
        public string Bill_toCustomerNo { get; set; }
        public string Bill_toName { get; set; }
        public string Bill_toName2 { get; set; }
        public string Bill_toAddress { get; set; }
        public string Bill_toAddress2 { get; set; }
        public string Bill_toCity { get; set; }
        public string Bill_toContact { get; set; }
        public string YourReference { get; set; }
        public string Ship_toCode { get; set; }
        public string Ship_toName { get; set; }
        public string Ship_toName2 { get; set; }
        public string Ship_toAddress { get; set; }
        public string Ship_toAddress2 { get; set; }
        public string Ship_toCity { get; set; }
        public string Ship_toContact { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime PostingDate { get; set; }
        public DateTime ShipmentDate { get; set; }
        public string PostingDescription { get; set; }
        public string PaymentTermsCode { get; set; }
        public DateTime DueDate { get; set; }
        public Decimal PaymentDiscount { get; set; }
        public DateTime PmtDiscountDate { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string LocationCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string CustomerPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public Decimal CurrencyFactor { get; set; }
        public string CustomerPriceGroup { get; set; }
        public int PricesIncludingVAT { get; set; }
        public string InvoiceDiscCode { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string LanguageCode { get; set; }
        public string SalespersonCode { get; set; }
        public string OrderNo { get; set; }
        public int NoPrinted { get; set; }
        public string OnHold { get; set; }
        public int Applies_toDocType { get; set; }
        public string Applies_toDocNo { get; set; }
        public string BalAccountNo { get; set; }
        public string VATRegistrationNo { get; set; }
        public string ReasonCode { get; set; }
        public string GenBusPostingGroup { get; set; }
        public int EU3_PartyTrade { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string VATCountryRegionCode { get; set; }
        public string Sell_toCustomerName { get; set; }
        public string Sell_toCustomerName2 { get; set; }
        public string Sell_toAddress { get; set; }
        public string Sell_toAddress2 { get; set; }
        public string Sell_toCity { get; set; }
        public string Sell_toContact { get; set; }
        public string Bill_toPostCode { get; set; }
        public string Bill_toCounty { get; set; }
        public string Bill_toCountryRegionCode { get; set; }
        public string Sell_toPostCode { get; set; }
        public string Sell_toCounty { get; set; }
        public string Sell_toCountryRegionCode { get; set; }
        public string Ship_toPostCode { get; set; }
        public string Ship_toCounty { get; set; }
        public string Ship_toCountryRegionCode { get; set; }
        public int BalAccountType { get; set; }
        public string ExitPoint { get; set; }
        public string Correction { get; set; }
        public DateTime DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string PaymentMethodCode { get; set; }
        public string ShippingAgentCode { get; set; }
        public string PackageTrackingNo { get; set; }
        public string Pre_AssignedNoSeries { get; set; }
        public string NoSeries { get; set; }
        public string OrderNoSeries { get; set; }
        public string Pre_AssignedNo { get; set; }
        public string UserID { get; set; }
        public string SourceCode { get; set; }
        public string TaxAreaCode { get; set; }
        public int TaxLiable { get; set; }
        public string VATBusPostingGroup { get; set; }
        public decimal VATBaseDiscount { get; set; }
        public string PrepaymentNoSeries { get; set; }
        public int PrepaymentInvoice { get; set; }
        public string PrepaymentOrderNo { get; set; }
        public string QuoteNo { get; set; }
        //public string Work Description { get; set; }
        public int DimensionSetID { get; set; }
        public int PaymentServiceSetID { get; set; }
        public string DocumentExchangeIdentifier { get; set; }
        public int DocumentExchangeStatus { get; set; }
        public string DocExchOriginalIdentifier { get; set; }
        public int CoupledtoCRM { get; set; }
        public string DirectDebitMandateID { get; set; }
        public int CustLedgerEntryNo { get; set; }
        public string CampaignNo { get; set; }
        public string Sell_toContactNo { get; set; }
        public string Bill_toContactNo { get; set; }
        public string OpportunityNo { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string ShippingAdvice { get; set; }
        public string PostingfromWhse_Ref { get; set; }
        public string RequestedDeliveryDate { get; set; }
        public string PromisedDeliveryDate { get; set; }
        public string ShippingTime { get; set; }
        public string OutboundWhse_HandlingTime { get; set; }
        public string ShippingAgentServiceCode { get; set; }
        public string Receive { get; set; }
        public string ReturnReceiptNo { get; set; }
        public string ReturnReceiptNo_Series { get; set; }
        public string LastReturnReceiptNo { get; set; }
        public string AllowLineDisc { get; set; }
        public string GetShipmentUsed { get; set; }
        public string AssignedUserID { get; set; }
        public string Cash_flowcode { get; set; }
        public string ShipmentStartTime { get; set; }
        public string CreateReceipt { get; set; }
        public string Applies_toBillNo { get; set; }
        public string Cust_BankAcc_Code { get; set; }
        public string Pay_atCode { get; set; }
        public string DebitMemo { get; set; }
        public string SeriesGroup { get; set; }
        public string BudgetName { get; set; }
        public string Year { get; set; }
        public bool FacturaCAF { get; set; }
        public string No_Compromisso { get; set; }
        public string CodigoPedido { get; set; }
        public string DataServ_Prestado { get; set; }
        public string Observacoes { get; set; }
        public DateTime DataEncomenda { get; set; }
        public string PeriododeFact_Contrato { get; set; }
        public string Observações1 { get; set; }
        public string ContractNo { get; set; }
        public decimal ValorContrato { get; set; }
        public string ReportIDOriginal { get; set; }
        public string RelatedInvoice { get; set; }
        public string Userpreregisto2009 { get; set; }
        public string ResponsabilityCenterCode20 { get; set; }
        public string FunctionAreaCode20 { get; set; }
        public string RegionCode20 { get; set; }
    }
}
