using System;

namespace Hydra.Such.Data.Database
{
    public partial class QuestionarioFornecedorGestaoAmbiental
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public int Versao { get; set; }
        public string ID_Fornecedor { get; set; }
        public string Fornecedor { get; set; }
        public string Actividade { get; set; }
        public string Responsavel { get; set; }
        public string Funcao { get; set; }
        public string Telefone { get; set; }
        public string Procedimento { get; set; }
        public string Email { get; set; }
        public bool? Resposta_11_Sim { get; set; }
        public bool? Resposta_11_Nao { get; set; }
        public bool? Resposta_11_NA { get; set; }
        public string Resposta_11_Texto { get; set; }
        public string Resposta_12_Texto { get; set; }
        public string Resposta_13_Texto { get; set; }
        public bool? Resposta_21_Sim { get; set; }
        public bool? Resposta_21_Nao { get; set; }
        public bool? Resposta_21_NA { get; set; }
        public bool? Resposta_22_Sim { get; set; }
        public bool? Resposta_22_Nao { get; set; }
        public bool? Resposta_22_NA { get; set; }
        public string Resposta_23_Texto { get; set; }
        public string Resposta_2_Texto { get; set; }
        public bool? Resposta_31_Sim { get; set; }
        public bool? Resposta_31_Nao { get; set; }
        public bool? Resposta_31_NA { get; set; }
        public bool? Resposta_32_NA { get; set; }
        public string Resposta_32_Texto { get; set; }
        public string Resposta_3_Texto { get; set; }
        public bool? Resposta_41_Sim { get; set; }
        public bool? Resposta_41_Nao { get; set; }
        public bool? Resposta_41_NA { get; set; }
        public bool? Resposta_42_Sim { get; set; }
        public bool? Resposta_42_Nao { get; set; }
        public bool? Resposta_42_NA { get; set; }
        public string Resposta_43_Texto { get; set; }
        public string Resposta_4_Texto { get; set; }
        public bool? Resposta_51_Sim { get; set; }
        public bool? Resposta_51_Nao { get; set; }
        public bool? Resposta_51_NA { get; set; }
        public bool? Resposta_52_Sim { get; set; }
        public bool? Resposta_52_Nao { get; set; }
        public bool? Resposta_52_NA { get; set; }
        public string Resposta_5_Texto { get; set; }
        public bool? Resposta_61_Sim { get; set; }
        public bool? Resposta_61_Nao { get; set; }
        public bool? Resposta_61_NA { get; set; }
        public bool? Resposta_62_Sim { get; set; }
        public bool? Resposta_62_Nao { get; set; }
        public bool? Resposta_62_NA { get; set; }
        public bool? Resposta_63_Sim { get; set; }
        public bool? Resposta_63_Nao { get; set; }
        public bool? Resposta_63_NA { get; set; }
        public bool? Resposta_64_Sim { get; set; }
        public bool? Resposta_64_Nao { get; set; }
        public bool? Resposta_64_NA { get; set; }
        public bool? Resposta_65_Sim { get; set; }
        public bool? Resposta_65_Nao { get; set; }
        public bool? Resposta_65_NA { get; set; }
        public string Resposta_6_Texto { get; set; }
        public bool? Resposta_71_Sim { get; set; }
        public bool? Resposta_71_Nao { get; set; }
        public bool? Resposta_71_NA { get; set; }
        public bool? Resposta_72_Sim { get; set; }
        public bool? Resposta_72_Nao { get; set; }
        public bool? Resposta_72_NA { get; set; }
        public string Resposta_7_Texto { get; set; }
        public bool? Resposta_81_Sim { get; set; }
        public bool? Resposta_81_Nao { get; set; }
        public bool? Resposta_81_NA { get; set; }
        public bool? Resposta_82_Sim { get; set; }
        public bool? Resposta_82_Nao { get; set; }
        public bool? Resposta_82_NA { get; set; }
        public bool? Resposta_83_Sim { get; set; }
        public bool? Resposta_83_Nao { get; set; }
        public bool? Resposta_83_NA { get; set; }
        public string Resposta_8_Texto { get; set; }
        public bool? Resposta_91_Sim { get; set; }
        public bool? Resposta_91_Nao { get; set; }
        public bool? Resposta_91_NA { get; set; }
        public string Resposta_9_Texto { get; set; }
        public bool? Resposta_101_Sim { get; set; }
        public bool? Resposta_101_Nao { get; set; }
        public bool? Resposta_101_NA { get; set; }
        public string Resposta_101_Texto { get; set; }
        public bool? Resposta_102_Sim { get; set; }
        public bool? Resposta_102_Nao { get; set; }
        public bool? Resposta_102_NA { get; set; }
        public string Resposta_102_Texto { get; set; }
        public bool? Resposta_103_Sim { get; set; }
        public bool? Resposta_103_Nao { get; set; }
        public bool? Resposta_103_NA { get; set; }
        public string Resposta_103_Texto { get; set; }
        public string Final_Responsavel { get; set; }
        public DateTime? Final_Data { get; set; }
        public DateTime? DataHora_Criacao { get; set; }
        public string Utilizador_Criacao { get; set; }
        public DateTime? DataHora_Modificacao { get; set; }
        public string Utilizador_Modificacao { get; set; }
    }
}
